package com.github.diceroller.equivocals

class InMemoryEquivocalsCardRepository : EquivocalsCardRepository {

    override fun getRandom(type: TaskType): Card? {
        val card = data.filter { it.type == type }.shuffled().firstOrNull()

        return card?.copy(task = decypher(card.task).replaceFirstChar { it.uppercaseChar() })
    }

    private fun cypher(text: String): String {
        return text.mapIndexed { i, char ->
            val keyChar = CYPHER_KEY[i % (CYPHER_KEY.length - 1)]

            when (val mappedChar = abcMap[char]) {
                null -> char
                else -> abc[(mappedChar + abcMap[keyChar]!!) % abcMap.size]
            }
        }.joinToString("")
    }

    private fun decypher(text: String): String {
        return text.mapIndexed { i, char ->
            val keyChar = CYPHER_KEY[i % (CYPHER_KEY.length - 1)]

            when (val alpha = abcMap[char]) {
                null -> char
                else -> abc[(alpha - abcMap[keyChar]!! + abcMap.size) % abcMap.size]
            }
        }.joinToString("")
    }

    companion object {
        private const val CYPHER_KEY = "экивоки"
        private const val abc =
            "абвгдежзийклмнопрстуфхцчшщъыьэюя" +
            "АБВГДЕЁЗЖИКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ" +
            "abcdefghijklmnopqrstuvwxyz" +
            "ABCDEFGHIJKLMNOPQRSTUVWXYZ" +
            "1234567890" +
            "./ -:&,"
        private val abcMap = abc.mapIndexed { i, c -> c to i }.toMap()

        private val backwardsDesc = "Наоборот"
        private val wordsDesc = "Объясни словами"
        private val drawingDesc = "Нарисуй"
        private val crocodileDesc = "Покажи жестами"
        private val yesNoDesc = "Да/Нет"

        private val eqDrawBlind = "Нарисуй с закрытыми глазами"
        private val eqThing = "Тварь/Штука"
        private val eqRetarded = "Объясни как умственно отсталый"
        private val eqBrands = "Объясни бренды"
        private val eqHumming = "Напой песню без слов"
        private val eqGames = "Объясни игры"
        private val eqSoundsOnly = "Объясни звуками"
        private val eqBands = "Спой песни исполителей"

        private val data: List<Card> = listOf(
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "ЮпхзЕфэжщрпкФфи"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "eкрйМцЕьДуН"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "gцчрюьЛсиоуГВчрз"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "jпфрщшАтЗ"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "aкпкпкАкхжьм"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "oьрчььяшшзытВ"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "pъипянНпщуцъЛмифК"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "AфщсухЖтитъэО"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "oкфрцсЛхЗшцИ"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "aпсоъкОьнт"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "aърптпякуют"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "jшуртшГпхэ"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "pкшвыьЕчц"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "ЯышвАшОьД"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "hкшвыьЕфынИ"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "oэчзюеИкшкьеюъцу"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "oшюкьчЕфи"),
            Card(CardTheme.ChertiYellow, TaskType.BACKWARDS, backwardsDesc, "oшуюВпБррр"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "CейзюпАшкрчеЛяшвычЕф"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "gьимнеМъцъБ"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "qБнпцфшБитьоВИгпоеРоинучЗп"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "cъндочшжгуАшЖтювйъЛыщкчыЗшлрйкЁьр"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "pкткуеИЕщнцеЗъГуцчШпгсьВЖт"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "pЕгнББХпз:ЕпИещвГкН"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "ЯшуряЕшыъэыэПек:фтЖкэ"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "/P3P29"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "jкшнусЛчщмцушлинуь"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "jшопьеТкфушэЫечтьыЩлы"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "ЯЕгхрхВБнпИ"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "ЯынойнРойвч"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "hкткуеЖЖмкйчэекзюлЖЖмз"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "eчизЁЁшБърнеМшмтБнэ"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "wкщ:ркХеъзщпСшх:цсшштпоеМшузАтП"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "AщцмятБчиБйыИшув"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "vэф:щпКтхушшАшгсюшОщнмАк"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "аRгYSV:"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "kэгсоъВчДбйчРер:ЕьЛ?"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "pктвНеИкузыЁЗкЗбйкшыърщЁЗшгжюИКт"),
            Card(CardTheme.ChertiYellow, TaskType.WORDS, wordsDesc, "lчгсщшБшхрятПещмБоЛэфкуц"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "eмымцеБкяк"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "jпсмяеОпту"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "gншвАЁшчи:БфРхнну"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "pкф:ЕпНЁкк"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "oпшзскшыйтцхшлшрртшыГпБ"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "nкт:эъЛыъвАЕ"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "hшугоыЛюь"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "jкъзБВ"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "nшх:БтДхр"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "oьыжяшяпъ"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "aърцВтКоцт"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "jшпеьлЛухБ"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "hхыгйщЛхмпцф"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "ЮппжьцКЕс"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "mткрйышьцооьЛц"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "uпъэюпшчитцыРЖ"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "hшфсКЖПпшпИушннпцу"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "lщитИВЕ"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "fпхуштЁешвхнЛмцт"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "pпътооЩещоуъПт"),
            Card(CardTheme.ChertiYellow, TaskType.DRAWING, drawingDesc, "hъиуыкЬеАмьхэ"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "qефзыИшъимйщНшщфоьШ"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "ЭфынйнЛхыгоИшктхщк"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "pпъмоеЖпъ:&,"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "lнытДЕшБнтют"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "CеъзпИшэщнИВэх"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "qлнтцьВещрпкЗэз:НеИпмкАтНэЁ"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "Яын:юпХпхрнеИкфвнеЬелзч"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "ЮкймцеБпшхАыЬепвйыэяит"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "ЭннпАетза/"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "cррмБеМшхБАчЛ"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "iштрйъЛфц"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "oпгнНеяте:яьНкмвчеЕефзюсКт"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "jкузыпФфц:этяк"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "oтщфуцэемвБчЛм"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "aшч&яьЛщ"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "aчрнКеМшгуштБфн"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "eкттИьэИгсцАУк"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "oфиицеМкшрщЁшшъ:ркЁжьвН"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "mпшжухЗкгпцфЕьГ"),
            Card(CardTheme.ChertiYellow, TaskType.CROCODILE, crocodileDesc, "jшуртшЁеязщшяптбйлШыътуп"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "bкяв"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "oпкзючЛпгщуъПкхррш"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "iпхкыыЗтс:эъЛычзшь"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "hкпвыЁ"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "aкштцеМшъфуъ"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "hмрй"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "mшЕф"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "лYWO"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "sшлдоъПы"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "Якфсцъ"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "Эуьры"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЮтуюНъБ"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "vкАнИф"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "jпф"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "mткр"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЮэтзА"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "vкфсочОфцз"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЭчлнцИ"),
            Card(CardTheme.ChertiYellow, TaskType.YES_NO_PUZZLE, yesNoDesc, "jкуцьу"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqDrawBlind, "mткрхкяъ"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqRetarded, "oьысьъшццйсшятхэ"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqBrands, "nшщеюкИ\nЁноьшкВыИ\nРДочЛмЩмцуйьШкшшпкО"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqHumming, "pър:юпЗт\nрыВшИхтппшэрюшхШ\nшэЗхЖешшЖоЫпо"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqThing, "pктрщпКо"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqGames, "05QVO2шRMT3\nеRM:ZKд4гQTеж3\nмВоДооф"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqSoundsOnly, "mткр"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqBands, "mшшпьюЕхДоИ\nЫътйфэХц\nU 3еOU:3PшKгF37,"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, "Покажи фильмы", "eкузЕЁшчи:тчЛек:пъЫнлз\nсШърБМВХрщучЕП\nпъэь"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, "Объясни фильмы", "oфкрхЁшыхзс\nНЖйщКЁЬ\nюзЁ"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, "Наоборот и значение", "kтлкщтОь"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, "Наоборот и значение", "bтэрАшИтЗ"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, crocodileDesc, "oейхГьШжйвюкТьГ"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, wordsDesc, "qЗщ:очБпшуьч\nъВюКкЬрпь\nьЖтшшяыТкч"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqDrawBlind, "ЮштвщеКкщфц"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, "Покажи фильмы", "oьшкэьЕснтЁк\nцнтЛлУ\nщшюыЪЗю"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, backwardsDesc, "aшкБфтЁеъиррЕф"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqBrands, "hти\nМлХДДь\nцРфяэютЩк"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, eqBrands, "aхцгБы\nчЗюпЗЪнуАшЗ\nЕщшюкУеятпт"),
            Card(CardTheme.ChertiYellow, TaskType.EQUIVOCALS, wordsDesc, "ЮктвюоЕ\nоохщЛцть\nцЖтАтКт"),


            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "AчъзюшОнннК"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "jшпеьВПэшо"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "oьцъожАшкпьсэо"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "bпфрАтякърюЕ"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "gцижфтКкшкБц"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "rшърсъэюртьмэьД"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "mкшуухПкхе"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "pшузюкКьхряьЩ"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "ЯшуюэпНьрпспН"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "ЙштоьфЗ"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "bкфгщоЛъ"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "aпхжуъКшдпууПъинКчШу"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "bъимьчЛъцитпКчГл"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "qщцтььЛыъю"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "pкфвсшФт"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "pЕтдожАърнК"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "hшуршшЖЁякш"),
            Card(CardTheme.ChertiPink, TaskType.BACKWARDS, backwardsDesc, "aхруАэОт"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "CецчюкКИЁ:ппНпл"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "jЕфтоеьехзйсВмил"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "oхыщоуКЕс:штюпшсочЗ"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "fткбйАВхз:ьъВх"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "oпфюйщЬьхкДеяшгнпэ"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "Яын:ркХтгдьхЛыГ:кеЪьц:эВВчршо"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "aкфвцхРБиАЗкЬеукЕтКфи:яьНкыуо"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "bкгфКюР"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "Юпп:тмРягжрпКкмшоьЩ"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "kэгфьнБкггБоРеозщкПЁгБ"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "jтххАэшоцгомЕхгйоеНкпеьмЛъГ"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "rьцтйыэцГлйрэорпо"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "kпгйумэуз:реАхиййоэц"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "wкщ:реАхиййоэц"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "ЯЕгщАшьехзйлШхр:реИтххятКытз?"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "uпшфочЛмюэймшсЁйцчЛ"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "hшувълЕИгсцфФпшййчВечтуоОьидщИВь"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "bми:реюпщмьчВБхряьЕ"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "AхнеочПчГлйюэыцп"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "hкткуеЕонкйИшщшктэИЕквМ"),
            Card(CardTheme.ChertiPink, TaskType.WORDS, wordsDesc, "aшмйцхЖкгсьоБпшицмэпъ:штКндмьчАк"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "jтщфуъшыцуцыЗк"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "jИщрйпАшшв"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "mърпуыЕеЕпАпНшщеухЩ"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "aшурршЖшфмоеяелрщшяп"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "hкт:шкЗкъю"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "hэтноеЗшужБчэ"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "7иL"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "bкшзъ"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "Япсс"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "mъцеюкИцруА"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "oхрйуъЕч"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "oьрмуъМкт"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "bЖхв"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "cррмБеМшхБАчЛ"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "mкумоч"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "oьрмуъМкт:реПпузсъэцн"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "oьц"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "oшйвЕтЁекрюы"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "CетрАтЗйгфИеЗшъкш"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "pшхпоеПшхвщЁКттв"),
            Card(CardTheme.ChertiPink, TaskType.DRAWING, drawingDesc, "pээнц"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "jпфрщшАтЗ"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "oпкзючЛпгщуъПкхррш"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "ЭуъкЁчЕфгпоеИтунцшК"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "hшшрщпякгжюкИ"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "nтявюошыисьнЛм"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "ЯшуряЕшчн:ящЕАГбйнЖкпвйчВешзячЕАГ"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "CейюМеГпхыцчштгжуьВу"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "pкф:эъЛмнтНЖП"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "mшсжБеМъцдуъЫ"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "mкътцкНягмцъЕху"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "aкшнуцшВнлш"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "gншррЕВеидАшИкъэ"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "bэй:яьЛтъ:рпЗшкрч"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "qефзыИшпщфКеПшщф"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "jкс:ГкИщщ"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "aпсопшЁечтььЕмгR7Z"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "jкуюЕтЗтгиоъЬьгъоВЖЕт"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "hьц:пэБпъ:ъЕПЁгсьыРоы?"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "ЮэурЕфэещ:ъкЗшф"),
            Card(CardTheme.ChertiPink, TaskType.CROCODILE, crocodileDesc, "mпшзюЕяехвйщЛфытцьЩ"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "nшузрфэ"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "oтфзВъЛщцнКыЗтс:пэЖЁквю"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "mпхйо"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "qфынухВ"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "bрцвыеНшынцчА"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "hкуюНч"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "AхДц"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "еOTGU24W"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "nшожуыПмц"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "rкъв"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "mхипЁпП"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЮшынцчА"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "cъндоч"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "bъиоо"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "mхнляьВуАп"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "hшуюДш"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "vфцно"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "hшшец"),
            Card(CardTheme.ChertiPink, TaskType.YES_NO_PUZZLE, yesNoDesc, "aпшоцшКк"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, eqThing, "oшщкяфэек:шшЖЁюр"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, eqRetarded, "nкщущшВчрзйцЛсозЕфэ"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, eqBrands, "ЮпурюэОытвНеЗшщоуьЕфи\nчэЩрфштеТпгепнЧцЕьхлМтк\nЗшШррфэеРИгфЛъНпьмЗт"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, eqHumming, "pър:эшЖшщмц\nИехуоршокАЁеМеньчБШх\nхылЕед:ЗшХю"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, eqThing, "hээпНеКкгтоуЛчн"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, eqDrawBlind, "ЮкхвышяЕс:ГхВл"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, eqSoundsOnly, "hшьз"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, eqThing, "jкькН"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, wordsDesc, "hкт:рЕюъифКыЬерййюЖкхв"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, "Наоборот и значение", "ЭчцоцИ"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, "Наоборот и значение", "oтйвютП"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, eqThing, "AфрдьфЕ"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, "Покажи с закрытыми глазами", "eклвтфэемэюЕ"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, "Объясни фильмы", "kЁЁ&чшНфз:ыЁЫжсрюф\nьточуэпуштЁшкЗяьЕФ\nэшВсМер:МэЩВы"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, backwardsDesc, "rъруАкЁхц:юкЗкфвшкСш"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, crocodileDesc, "kшкэчеПмцлйщНтЗфухЩ"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, "Спой песню", ":5UG2\nгKUO748SV\nЗшШрщжйтшъБь"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, "Спой песню", "ЯкузютЁефзщкБсн\n4V4MMD3\n5VIEYе89MFйZ8K1"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, drawingDesc, "ЭмнпАэНк\nшшЖКфГБы"),
            Card(CardTheme.ChertiPink, TaskType.EQUIVOCALS, eqBrands, "mткрйышсилДпИ\nсощэшфрфпп"),


            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "pънсуьэьД"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "nэтрэшГкъку"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "mЁЗпьцРефрюпшщц:шшЖпхр"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "oьшвГеЕехзыкятщфКеяеувяжяплвяп"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "pшщмо"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "mъррпшБърфКыЬ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "ЭчъкэпНычкюкКь"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "hтчБАшЗ"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "ЯчнйощКш"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "fкмкык"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "oфшзэИшынттАВ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "hхихяьНшьрптЬ"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "jэшвЁфЕ"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "eктвАтПЁгушкКоин"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "iпхю"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "kпкэышОтфвНеЖплмьыПЁггИьЕИ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "hшхуучОэщ"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "aхийоеНкпгурэхруК"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "mшмнцсШмифКыЬ"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "hшфсщтИпхф"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "eкккяьКтт"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "bктфцхЛытрэ"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "gсгршчэемхщш"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "pъцеоьВхДпИу"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "Яшхю"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "ЯтшфБкЖЁхэчеНшфвы"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "oпшжДпВотв"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "lьгдьъЛьгсьмЛъцф"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "ЮкйрЕфЕек:фтяшъз"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "lщГф"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "CеЕфцеАшшэймшьннумЕсцтуеятмвщ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "oкмръкДшэкяь"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "sшъюйнЖкп:рЕЗшук"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "kпчтцхЕБхэчеГпщф"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "fкуряьЩ"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "bпкхЁфэйгоьрКшгуймэцр:эшДчимьцЕьДуН?"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "oшйносКтъзщЁКтюв"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "vмнжяфэИгууцЩИ"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "nппвАЁшщшвроРжфвАфР"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "wптрАфэ"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "Aьц:эъЛыърйщНкпжытЗетвшшЁжър!"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "nпчхАкУтЗ"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "qцгйоеНкпхъеДкэрттП"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "fпфвычЕАи"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "gчъхцАЕИ"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "mъцоьБЕьД:ышАт"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "ЯшпнМлЖпхпоИ"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "jкътоыКтявАЁ"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "kкцыБщЩ"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "qыъвщшОьД"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "bЕАвАЁшчи:щкБкх"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "pпфсуъэцнпА"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "hшфршеяелрюхВ"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "oмржочЕпгдяхВщыА"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "mырчьхЛн"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "kпокАЁОИ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "jпувыяЛхрм"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "Эощмцпшцымц"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "mшуАптХЁгкйфЛсув"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЯшщфьъА"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "bпъзшьЛъгнфт"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "sкшвшьВъруАтЗк"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "oнцтоьЩецфйыПЕмв"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "uкс:экТчнфймВчрмьц"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "oтхБш"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "kпшдцВЗтгъохЬь"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "gчъзщхВфъхох"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "hкт:хкшфиоучКшс:яьВчцл"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "nкщфоИПЁгрАеРцрнучЕИ"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЭчъкэкПтЗ"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "ЯпътучЕАи"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "Яоцчышяпхку"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "bпшиоьЩеычьеяшщфюш"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "ЮэшБйЗИшюкч"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "mърдИБЗк"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "bповрЖ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "oкфрюпэхрйоАЕИ"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "ЯшуряЕшоГгьц"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "mъцъъЕАчыфК"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "sтътьыПЁ"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "hэчкАЁОИ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "ЮпщсуъОщнмАтячЗм"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "ЯеузяэшъийткякууНеПшчрюеБъцдьыВфи"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "mънуъЕЗкъюяИ"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "oфкрхчЬф"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "uэкуАмэекзюэЫГрч"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "bшщфьтКыъдь"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "mшмущэХтквАЁ"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "ЯшмкАЁшси:ышО"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "eэм"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "hэуюАэНчГлйВЛф"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "nкпдюкПчрм"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "bэАвйэХхи:реМИъмц"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "oБрфоьЩекрюшК"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "sшузютЗ"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "vтшрштЁеозяь"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "gщцчьчБърм"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "jшшрхеМшгмьрВ"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "oкямьмэьД"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "hърм"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "kпггБоЕеукГшьечршкшшхрйьЕяц"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "AщрнущПшрж"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "oфысоИшцыияфэИгущпДк"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "kпязъеЗъГфК"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "oьшвяьЩ"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "gычэАкКтн:яхэмцл"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "oкфрьлИкх"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "mъцдуъЗкгпоеяВрдьыПЁ"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "vпкзщтПЁгхЁкИт"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "aпхкч"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "lщнъцьЩ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "oпхуьъЕфи"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "mъцлАтшшлрыЁштгдьоР"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "kпфвНеОАнпо"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "gыъзютЗк"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "uэкуАмЛеуршьЬ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "jэозыпКкккяьКтюв"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "kпгуИщЩефпуеОшуюйчэешвыэ"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "lыърюшГчцбйшЗъиъучЛ!"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "qордщпКтн"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "ЯпшкАЁшчи:яхЛмц"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "aшурршЗъыиучЕп"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "ЯьцтьпшоГчочЕп"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "qщиуАЁшмгещкДкэ"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "hкчтцс"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "oцшвт"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "nкпрЕкНшквытВ"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "bэъюйчэефрщшЗш"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "hшАмцеОфшзпэПехвйоРВн"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "qщшБъыПмц"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "iЖйрркПЁщБ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "oтфхщИКьтв"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "lохрчеЖпкрч"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "pэлртэИ"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "AыъзА"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "iпйзхтПЁ"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "oптуьщэьцньн"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "lлхБАЁштгсщкЗкъю"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "mпявщЁЗк"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "iктръфэ"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "bкъюйхВГи"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "hтхзяьВьрмо"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "bпшиоьЩыЗ:хкшыцньцЕчтх"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "jшъвАЁшчи:Бы"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "kклньыПЁ"),
            Card(CardTheme.Sensations, TaskType.BACKWARDS, backwardsDesc, "oфшръчЛыъю"),
            Card(CardTheme.Sensations, TaskType.WORDS, wordsDesc, "oхижьыПъиуАчЕф"),
            Card(CardTheme.Sensations, TaskType.DRAWING, drawingDesc, "mърпМяэьДуН"),
            Card(CardTheme.Sensations, TaskType.CROCODILE, crocodileDesc, "ЯЕтвпхРБрдоьЩыЗ"),
            Card(CardTheme.Sensations, TaskType.YES_NO_PUZZLE, yesNoDesc, "lщиуышОьД"),


            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "oфккп"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "hшхцБчБэщ"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "aгЖ Ргkгf "),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "vштрщкБчиБйхЬныъшк"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЯкщкщтОф"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "mшшфох"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "bкфгщоЛъ"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "ЯшщмюпХкЁыцушфиоучЩ"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "jттуАэНкгхъпКЁАзытЬепхпшя"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "Эфюкь"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "iпчтуфЛчщмьпшсцнььЛ"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "iпчтуфЛч"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "mшяфцеЮппеьхЛмГлйЧЕф"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "eпуюумэънпцп"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "mшухъчэ"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "mкурЕфэеКрщкКжмзЪшНьи"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "jшпеьВИЕл"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "mъГфшшщЩръБГВпгсуъЛ"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "mэьцучБэс"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "hънуАъэр"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "bчндытЗеЪръкшЪнжтхэ"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "jпъвъшНюцоон"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "pэшпцъшьшзГеяшуъулКттрр"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "lцыфйщэцЗфц"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "jклн"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "oмрфуъшшъ:ЪшЖхр:bсЖт"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "aъЗйышЗъцдшк"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "aъноББэИгкрк"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "mшюзщэЁемзъпКьцто"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЭствпкК"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "pкспоИшфцоыкПк"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "bэшояьНкхе"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "hшщрчеМпшзБхЛф"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "iЖйррчЛпгйухЩп"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "kклвччэ"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "ЮэпкычэИгсохЛБтв"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "eпшмохЛеНкыкЖпо"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "mшокюкПпукйыИпшфц"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "lыърщлВчнл"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "hмржттФ"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "oхрдьБКшн:этяш"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "bшуеьщРщщ"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "Эмижоеhпмвръэ"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "fткрсхЛь"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "aшйнцч"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "mхифВшНци:ееод/"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "lхукркКонт"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "ЯЕшхЕкЁжтръчэьи"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "iпккАкУтЗ"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "bрцвыеnшынцчА"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "eкйвяьЛмцщыЕЁепврьНкт"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "fкйтьыЖт"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "oшккыкЬечрЕьэ"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "eшурАшВеЗлДш"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "jпшнцч"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "cрнжыпячГлйщНшшрш"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "pъипяюЕнытоАЕИ"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "iпъхЕтЁечрюшТ"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "jъимьлЛънш"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "hкфкы"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "gыязхкПпуюыЕЁеАмою"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "mкшуБхПкхе"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "kкйрюеМшгхГшБэгйоеИпъньу"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "ЯтпиоГэИгчцрЕчи"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "«ЩшкттНк»"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "jкэрртЗектуцВчр"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "mшуфуъАпсуА"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "bшфвЁчЕугящЁС"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "«ОГтНмШугмььВх»"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "mхимякшЦртАх"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "hкшфоеИкшртпНшк"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "hъышцкПэщ"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "bкшэйыИпшфц"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "eкчтуьКЕс:щпО"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "rпхкшы"),
            Card(CardTheme.HarryPotter, TaskType.WORDS, wordsDesc, "mэАмцеmпмжщ"),
            Card(CardTheme.HarryPotter, TaskType.BACKWARDS, backwardsDesc, "ЯсшэршМшъвъ"),
            Card(CardTheme.HarryPotter, TaskType.DRAWING, drawingDesc, "eктнНьЕпгмьыКшЗйИБЕИ"),
            Card(CardTheme.HarryPotter, TaskType.CROCODILE, crocodileDesc, "oшчньяяшщф"),
            Card(CardTheme.HarryPotter, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЯпукшкК"),


            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "nкпгцьКкЗ:юкДмнжучЗк"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "ЮхиеьнЛмнпцп"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "oпмкыкшмггьъЛоы:кеюпщ:реНпйть"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "oмржочЕпгдяхВщыА"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "pшямое0"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "eкйрщпякхкуйшщнтуоэЖБзуыЬечрщшяЕф:ээПпф"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "kпмряьэьцм"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "jэо:цеГпхвйшБчи:якПкхв"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "ЯшшмьмэьД"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "hкпвышяк"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "bкквчеМшозытИыЗ"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "aпъзюшОптуБкЖ"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "bми:якМшлвйщэъи"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "ЮъищыЕЁеъвыпУ"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "Aъцфцфэ"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "fтъюймЛелтуяВ"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "oмифьмОькр"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "oьшрцьЩелносЗт"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "mЕАпИушлЁуА"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "nкпдьо"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "hтщзччэИггоъШВхБ"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "jчцеьрВчщфрш"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "mшмтБрЗкгпумВыъэ"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "eкитшкКтъю"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "bппжуцЛчи"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "mттвэпН"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "kтфцьцэчтв"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "mшттоыКпъюйоЛеыъуу"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "oчЗфКеПпумБ"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "gсфзык"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "aкувыьКЕс:шкякузю"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "mъннМлЛонБытВ"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "Юшс&пкюк"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "hхнкАЁОИ"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "mшфрщмЗк"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "bтъБйщЛъцмо"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "ЮъимьыЛБнфочЕп"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "oхижшкЬечвюшФфи"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "oптуклЛцйв"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЮпшзъпКчцуАЁ"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "oьитИушъийръэьхкш"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "hшхфюкУпчшцИ"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "mпшдИушщитучЩехвйоВъндып"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "lъинКчШпгноыЗт"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЮОЩО"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "pЖузыЁшхЁгрт"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "nшлрышОпю"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "lьйкАЁшщитыИ"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "oмЗйоьЩыЗ:яеИкурщпПфцл"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЭщцнщшК"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "bпувйыВъмзЕчШп"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "oхиуАшЖЖйзД"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "oпфзюшшщц:щкяфио"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "aпшрчжЖЖйррчЕф"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "hштзАфэ"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "pтуккьЕхр:АпОьцбйрВчрчйтшчндуыПк"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "aпшооюНшмкА"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "lьгдьъЛьгсьмЛъцф"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "kшяпоИшлигьБЗк"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "jкуюЕтХчрм"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "hхыъо"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "ЯпътучЕАи"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "mъцъщкшхЁгьмЩйгйомЬхр:эшИтмрюЕ"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "ЯьцтоИшщцньмЕчтв"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "ЯхЁгцьЩыЗ"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "nкпнМлЕьД"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "nкпнББКтюв"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "hшхцуьКшдгБфВьхэчеМпшкьо"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "oфннуьшмгъшкСэ"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "aкшзъ"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "lыъвАЁОИгжюэДЁЗоц"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "nкпрЕкНшквытВ"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "aчнйтшшъийръэьи"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "fтъюйщЛхцдьушррйыЁЫ"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "mшюзщэЁ"),
            Card(CardTheme.LoveAndAround, TaskType.WORDS, wordsDesc, "qргйоцРргпумПпшсур"),
            Card(CardTheme.LoveAndAround, TaskType.BACKWARDS, backwardsDesc, "aънчьмЛохкш"),
            Card(CardTheme.LoveAndAround, TaskType.DRAWING, drawingDesc, "ЮшлкыИ"),
            Card(CardTheme.LoveAndAround, TaskType.CROCODILE, crocodileDesc, "qяииуъ"),
            Card(CardTheme.LoveAndAround, TaskType.YES_NO_PUZZLE, yesNoDesc, "oкфмо"),
        )
    }
}