name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./gradlew build

      - name: Deploy
        run: deploy ./build/libs/diceroller.jar
